######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 23:08:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
HEADERS += GeneralForm.h QCoin.h
SOURCES += GeneralForm.cpp main.cpp QCoin.cpp
