######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 14 01:37:34 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
HEADERS += Animator.h QCoin.h
SOURCES += Animator.cpp main.cpp QCoin.cpp
