######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 19:36:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
HEADERS += AbstractWindow.h Animator.h FreeForm.h 	MotionForm.h QCoin.h
SOURCES += AbstractWindow.cpp Animator.cpp FreeForm.cpp main.cpp MotionForm.cpp QCoin.cpp
