######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 14 23:13:50 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
HEADERS += Animator.h AnimatorWindows.h QCoin.h
SOURCES += Animator.cpp AnimatorWindows.cpp main.cpp QCoin.cpp
