######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 8 01:48:22 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DoRegExp.h
SOURCES += RegexTester.cpp
