######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 29 15:09:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
SOURCES += arm.cpp
