######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 4 00:54:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
HEADERS += Animator.h QCoin.h
SOURCES += Animator.cpp \
           main.cpp \
           QCoin.cpp \
