######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 15:23:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt
QT += xml

# Input
HEADERS += MotionForm.h QCoin.h
SOURCES += main.cpp MotionForm.cpp QCoin.cpp
