######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 9 15:10:57 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
HEADERS += FreeForm.h QCoin.h
SOURCES += FreeForm.cpp main.cpp QCoin.cpp
