######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 8 00:59:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += RegexTester.cpp
