######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 30 03:26:02 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lCoin -lSoQt

# Input
HEADERS += QCoin.h
SOURCES += main.cpp QCoin.cpp
